  on:
    push:
      branches:
        - main
        - develop
    workflow_dispatch:
    pull_request:
  name: ci
  jobs:
    publish:
      uses: nr1etech/github-workflows/.github/workflows/javascript-library.yml@develop
      with:
        github-email: "365211+erikrj@users.noreply.github.com"
        github-name: "Erik Jensen"
        site-branch: 'main'
        publish-dir: "dist"
        node-versions: '[20,22]'
        publish-node-version: '22'
      secrets:
        deploy-key: ${{ secrets.DEPLOY_KEY }}
        npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
        app-id: ${{ secrets.RELEASE_BOT_ID }}
        private-key: ${{ secrets.RELEASE_BOT_KEY }}
